/**
 * Level definitions. Each level has a theme that drives colors/fog,
 * a size, coin count, obstacle count, enemy specs, and powerup count.
 * Difficulty ramps with level index.
 */
export const LEVELS = [
  {
    name: 'Meadow',
    theme: 'grass',
    sky: 0x87ceeb,
    skyTop: 0x4a9eff,
    skyBottom: 0xffe7c2,
    ground: 0x4a8f3a,
    accent: 0x8b5a2b,
    fog: [40, 100],
    size: 36,
    coins: 10,
    obstacles: 7,
    enemies: [{ type: 'patroller', count: 1 }],
    powerups: 1,
    parTime: 45,
    music: { mood: 'major', tempo: 110 },
    objective: 'Collect all 10 coins to open the portal.',
  },
  {
    name: 'Sand Dunes',
    theme: 'desert',
    sky: 0xf4a460,
    skyTop: 0xff9a55,
    skyBottom: 0xffd690,
    ground: 0xd2a55a,
    accent: 0x8b6f3a,
    fog: [35, 90],
    size: 40,
    coins: 14,
    obstacles: 10,
    enemies: [{ type: 'patroller', count: 2 }, { type: 'chaser', count: 1 }],
    powerups: 2,
    parTime: 60,
    music: { mood: 'major', tempo: 100 },
    objective: 'The dunes shift. Move quickly.',
  },
  {
    name: 'Frostpeak',
    theme: 'snow',
    sky: 0xb0d8e8,
    skyTop: 0x6a8fb8,
    skyBottom: 0xe6f0fa,
    ground: 0xeaf0f6,
    accent: 0x4a5a7a,
    fog: [30, 80],
    size: 42,
    coins: 16,
    obstacles: 12,
    enemies: [{ type: 'patroller', count: 2 }, { type: 'chaser', count: 2 }],
    powerups: 2,
    parTime: 70,
    music: { mood: 'minor', tempo: 95 },
    objective: 'Ice is slippery. Watch your step.',
    slippery: true,
  },
  {
    name: 'Emberlands',
    theme: 'lava',
    sky: 0x4a1010,
    skyTop: 0x1a0a14,
    skyBottom: 0xff5a2a,
    ground: 0x3a1a1a,
    accent: 0xff5522,
    fog: [25, 70],
    size: 44,
    coins: 18,
    obstacles: 14,
    enemies: [{ type: 'patroller', count: 3 }, { type: 'chaser', count: 2 }, { type: 'spike', count: 6 }],
    powerups: 2,
    parTime: 80,
    music: { mood: 'minor', tempo: 130 },
    objective: 'Lava pits everywhere. Stay sharp.',
  },
  {
    name: 'The Void',
    theme: 'space',
    sky: 0x05050f,
    ground: 0x14143a,
    accent: 0xaa55ff,
    fog: [30, 90],
    size: 46,
    coins: 22,
    obstacles: 16,
    enemies: [{ type: 'patroller', count: 3 }, { type: 'chaser', count: 3 }, { type: 'spike', count: 8 }, { type: 'boss', count: 1 }],
    powerups: 3,
    parTime: 100,
    music: { mood: 'minor', tempo: 120 },
    objective: 'The Cube King awaits. Defeat him and reach the portal.',
  },
];
